# Generated by Django 5.0.4 on 2024-05-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='slug',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
    ]
